import { downloadMediaMessage } from "@whiskeysockets/baileys"
import axios from "axios"
import FormData from "form-data"
import dotenv from "dotenv"
import Sticker from "wa-sticker-formatter"

dotenv.config()

/* =====================
   HELPER: MEMEGEN TEXT
   Memegen butuh format khusus:
   - Spasi diganti '_'
   - '_' diganti '__'
   - '-' diganti '--'
===================== */
const formatMemeText = (text) => {
  if (!text) return "_"
  return text
    .replace(/-/g, "--")
    .replace(/_/g, "__")
    .replace(/\s/g, "_")
    .replace(/\?/g, "~q")
    .replace(/%/g, "~p")
    .replace(/#/g, "~h")
}

/* =====================
   HELPER: GET MEDIA
===================== */
const getMediaMessage = (msg) => {
  if (msg.message?.imageMessage) {
    return msg.message.imageMessage
  }

  const quoted = msg.message?.extendedTextMessage?.contextInfo?.quotedMessage
  if (quoted?.imageMessage) {
    return quoted.imageMessage
  }

  return null
}

/* =====================
   MAIN FUNCTION
===================== */
const Smeme = async (sock, chatId, msg, text) => {
  try {
    // 1. Cek API Key ImgBB
    if (!process.env.BB_KEY) {
      return sock.sendMessage(chatId, { text: "⚠️ API Key ImgBB belum disetting di .env" }, { quoted: msg })
    }

    // 2. Cek Media
    const mediaMsg = getMediaMessage(msg)
    if (!mediaMsg) {
      return sock.sendMessage(
        chatId,
        { text: "⚠️ Kirim atau reply gambar dengan caption `!smeme atas|bawah`" },
        { quoted: msg }
      )
    }

    // 3. Parse Text
    // Menghapus command !smeme (case insensitive)
    const input = text.replace(/^!smeme\s*/i, "").trim()
    let [topText, bottomText] = input.split("|")

    // Format text sesuai aturan memegen
    topText = formatMemeText(topText)
    bottomText = formatMemeText(bottomText)

    await sock.sendMessage(chatId, { react: { text: "⏳", key: msg.key } })

    /* =====================
       DOWNLOAD IMAGE (Baileys)
    ===================== */
    // Kita harus menyusun ulang object agar sesuai format yang diminta downloadMediaMessage
    const messageType = Object.keys(msg.message)[0]
    // Jika reply, gunakan quoted, jika tidak gunakan message utama
    const mediaKey = mediaMsg === msg.message?.imageMessage ? msg : { message: { imageMessage: mediaMsg } }

    const buffer = await downloadMediaMessage(
      mediaKey,
      "buffer",
      {},
      { logger: console } // Logger opsional, mencegah warning
    )

    /* =====================
       UPLOAD KE IMGBB
    ===================== */
    const form = new FormData()
    form.append("image", buffer.toString("base64"))

    // Upload dengan timeout agar tidak hang selamanya
    const upload = await axios.post(
      `https://api.imgbb.com/1/upload?expiration=600&key=${process.env.BB_KEY}`,
      form,
      {
        headers: form.getHeaders(),
        timeout: 10000 // 10 detik timeout
      }
    )

    const imageUrl = upload.data.data.url

    /* =====================
       GENERATE MEME URL
    ===================== */
    // Memegen otomatis handle text, kita tinggal pass background url
    const memeUrl = `https://api.memegen.link/images/custom/${topText}/${bottomText}.png?background=${imageUrl}`

    /* =====================
       CONVERT TO STICKER
    ===================== */
    // OPTIMASI: Sticker formatter bisa terima URL langsung.
    // Kita tidak perlu download manual via axios lagi.
    const sticker = new Sticker(memeUrl, {
      pack: "Meme Sticker", // Bisa diganti nama bot kamu
      author: "Generated by Bot",
      type: "full", // 'full' agar gambar tidak terpotong (crop)
      quality: 70, // 70-80 sudah cukup bagus untuk WA
    })

    const stickerBuffer = await sticker.toBuffer()

    /* =====================
       SEND RESULT
    ===================== */
    await sock.sendMessage(
      chatId,
      { sticker: stickerBuffer },
      { quoted: msg }
    )

  } catch (err) {
    console.error("[SMEME ERROR]", err)

    // Error handling spesifik
    let errorMessage = "Terjadi kesalahan saat membuat meme."
    if (err.response?.status === 400) errorMessage = "Gagal upload ke ImgBB. Pastikan gambar valid."
    if (err.code === 'ECONNABORTED') errorMessage = "Koneksi timeout saat upload."

    await sock.sendMessage(
      chatId,
      { text: `⚠️ ${errorMessage}` },
      { quoted: msg }
    )
  }
}

export default Smeme
